repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.4"
    hooks:
      - id: ruff
        args: ["--select", "E,F,I001"]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
